tasks:
  - name: Configure workspace
    init: |
      go install golang.org/x/tools/cmd/goimports@v0.1.11
      go install golang.org/x/lint/golint@v0.0.0-20210508222113-6edffad5e616

vscode:
  extensions:
    - golang.go
